/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TubesPBO;
import static TubesPBO.uilogin.conn;
import java.awt.Color;
import java.util.Scanner;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
/**
 *
 * @author DZGIGABYTE
 */
public class pembayaranlanjut extends javax.swing.JFrame {
        private static final String DB_DRIVER = "com.mysql.jdbc.Driver";
        private static final String DB_CONNECTION = "jdbc:mysql://localhost/loket_ukt";
        private static final String DB_USER = "root";
        private static final String DB_PASSWORD = "";
        static Connection conn;
        static Statement stmt;
        static ResultSet rs;
    /**
     * Creates new form pembayaranlanjut
     */
    public pembayaranlanjut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keluar = new javax.swing.JLabel();
        riwayat = new javax.swing.JLabel();
        bayar = new javax.swing.JLabel();
        angkatan = new javax.swing.JTextField();
        prodi = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        waktudantanggal = new javax.swing.JTextField();
        namaadmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(495, 555));
        setResizable(false);
        getContentPane().setLayout(null);

        keluar.setAutoscrolls(true);
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(370, 430, 90, 40);

        riwayat.setAutoscrolls(true);
        riwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(riwayat);
        riwayat.setBounds(200, 430, 90, 40);

        bayar.setAutoscrolls(true);
        bayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(bayar);
        bayar.setBounds(60, 436, 80, 30);

        angkatan.setEditable(false);
        angkatan.setBorder(null);
        angkatan.setOpaque(false);
        angkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkatanActionPerformed(evt);
            }
        });
        getContentPane().add(angkatan);
        angkatan.setBounds(240, 290, 190, 30);

        prodi.setEditable(false);
        prodi.setBorder(null);
        prodi.setOpaque(false);
        prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiActionPerformed(evt);
            }
        });
        getContentPane().add(prodi);
        prodi.setBounds(240, 250, 190, 30);

        nama.setEditable(false);
        nama.setBorder(null);
        nama.setOpaque(false);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(240, 170, 190, 30);

        nim.setEditable(false);
        nim.setBorder(null);
        nim.setOpaque(false);
        nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimActionPerformed(evt);
            }
        });
        getContentPane().add(nim);
        nim.setBounds(240, 210, 190, 30);

        waktudantanggal.setEditable(false);
        waktudantanggal.setBackground(new java.awt.Color(255, 255, 255));
        waktudantanggal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        waktudantanggal.setBorder(null);
        waktudantanggal.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        waktudantanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktudantanggalActionPerformed(evt);
            }
        });
        getContentPane().add(waktudantanggal);
        waktudantanggal.setBounds(250, 60, 210, 22);

        namaadmin.setEditable(false);
        namaadmin.setBackground(new java.awt.Color(255, 255, 255));
        namaadmin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        namaadmin.setBorder(null);
        namaadmin.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namaadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaadminActionPerformed(evt);
            }
        });
        getContentPane().add(namaadmin);
        namaadmin.setBounds(250, 30, 210, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesImage/pembayaranlanjut.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(495, 555));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 495, 555);

        setSize(new java.awt.Dimension(495, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void waktudantanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktudantanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktudantanggalActionPerformed

    private void namaadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaadminActionPerformed

    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed

    }//GEN-LAST:event_nimActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiActionPerformed

    private void angkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angkatanActionPerformed

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_keluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaranlanjut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaranlanjut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaranlanjut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaranlanjut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaranlanjut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angkatan;
    private javax.swing.JLabel bayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel keluar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namaadmin;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField prodi;
    private javax.swing.JLabel riwayat;
    private javax.swing.JTextField waktudantanggal;
    // End of variables declaration//GEN-END:variables
}
