/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TubesPBO;

import java.awt.Color;
import java.util.Scanner;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author DZGIGABYTE
 */
public class uilogin extends javax.swing.JFrame {
        char b[];
        String a;
        private static final String DB_DRIVER = "com.mysql.jdbc.Driver";
        private static final String DB_CONNECTION = "jdbc:mysql://localhost/loket_ukt";
        private static final String DB_USER = "root";
        private static final String DB_PASSWORD = "";
        static Connection conn;
        static Statement stmt;
        static ResultSet rs;
      
    /**
     * Creates new form uilogin
     */
    public uilogin() {
       
        initComponents();
        this.setBackground(new Color (0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginbar = new javax.swing.JLabel();
        idbar = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        exit = new javax.swing.JLabel();
        tampilanlogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(680, 566));
        setSize(new java.awt.Dimension(680, 566));
        getContentPane().setLayout(null);

        loginbar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbarMouseClicked(evt);
            }
        });
        getContentPane().add(loginbar);
        loginbar.setBounds(230, 420, 220, 50);

        idbar.setBorder(null);
        idbar.setOpaque(false);
        idbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarActionPerformed(evt);
            }
        });
        getContentPane().add(idbar);
        idbar.setBounds(150, 270, 200, 20);

        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(150, 322, 200, 20);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesImage/exit.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(620, 20, 40, 40);

        tampilanlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TubesImage/TAMPILAN LOGIN.jpg"))); // NOI18N
        getContentPane().add(tampilanlogin);
        tampilanlogin.setBounds(0, 0, 680, 570);

        setSize(new java.awt.Dimension(680, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void idbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarActionPerformed
     
    }//GEN-LAST:event_idbarActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
  
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void loginbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbarMouseClicked

         a=idbar.getText();   
         b=jPasswordField1.getPassword(); 
         String temp = String.valueOf(b);
         String c,d,admin;
         admin ="admin";
         try{
         Class.forName(DB_DRIVER);
         conn = DriverManager.getConnection(DB_CONNECTION,DB_USER,DB_PASSWORD);
         stmt = conn.createStatement();
         String sql = "Select * FROM "+ admin;
         rs = stmt.executeQuery(sql);
         while(rs.next()){
           c = rs.getString("adm_nama");
           d=rs.getString("adm_password");
           if (a.equals(c)&&temp.equals(d)){
               System.out.println("berhasil");
               menuhome home = new menuhome();
               home.setUsername(a);
               home.setVisible(true);
               this.dispose();
               break;
           }
           else {
               System.out.println("anda suram nih passwordnya : "+c+" "+d);
            }
           }
         }
         catch (Exception e){
                 e.printStackTrace();
                 }
                
    }//GEN-LAST:event_loginbarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uilogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uilogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uilogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uilogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new uilogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JTextField idbar;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel loginbar;
    private javax.swing.JLabel tampilanlogin;
    // End of variables declaration//GEN-END:variables
}
